const tl = gsap.timeline({
  defaults: {
    ease: "power1.out"
  }
});

tl.to(".text", {
  y: "0%",
  duration: 1,
  stagger: 0.25
});
tl.fromTo(".slider", {
  opacity: 0
}, {
  opacity: 1,
  duration: 3,
  delay: 0.5
}, "-=1");
tl.to(".quote-container", {
  y: "-100%",
  duration: .5
}, "-=1");
tl.fromTo(".img-container", {
  opacity: 0
}, {
  opacity: 1,
  duration: .3,
}, ">");
tl.fromTo(".my-img", {
  opacity: 0
}, {
  opacity: 1,
  duration: 1,
}, ">");
tl.fromTo(".name-container", {
  opacity: 0
}, {
  opacity: 1,
  duration: .3,
}, ">");
tl.fromTo(".my-name", {
  opacity: 0
}, {
  opacity: 1,
  duration: 1
}, ">");
tl.fromTo(".objective", {
  opacity: 0
}, {
  opacity: 1,
  duration: .5
}, ">");
tl.fromTo(".objective-container", {
  opacity: 0
}, {
  opacity: 1,
  duration: 1
}, ">");
tl.fromTo(".about-container", {
  opacity: 0
}, {
  opacity: 1,
  duration: 1.5
}, ">");
tl.fromTo(".school", {
  opacity: 0
}, {
  opacity: 1,
  duration: 2
}, ">");
tl.fromTo(".skill-set", {
  opacity: 0
}, {
  opacity: 1,
  duration: 2
}, ">");
